;;; v-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from v-mode.el

(let ((loads (get 'v-mode 'custom-loads))) (if (member '"v-mode" loads) nil (put 'v-mode 'custom-loads (cons '"v-mode" loads)) (put 'languages 'custom-loads (cons 'v-mode (get 'languages 'custom-loads)))))
(autoload 'v-mode "v-mode" "\
Major mode for editing V files.

(fn)" t)
(setq auto-mode-alist (cons '("\\(\\.v?v\\|\\.vsh\\)$" . v-mode) auto-mode-alist))
(register-definition-prefixes "v-mode" '("v-"))

;;; End of scraped data

(provide 'v-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; v-mode-autoloads.el ends here
