;;; eglot-booster-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from eglot-booster.el

(defvar eglot-booster-mode nil "\
Non-nil if Eglot-Booster mode is enabled.
See the `eglot-booster-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `eglot-booster-mode'.")
(custom-autoload 'eglot-booster-mode "eglot-booster" nil)
(autoload 'eglot-booster-mode "eglot-booster" "\
Minor mode which boosts plain eglot server programs with emacs-lsp-booster.

The emacs-lsp-booster program must be compiled and available on
variable `exec-path'.  Only local stdin/out-based lsp servers can
be boosted.

This is a global minor mode.  If called interactively, toggle the
`Eglot-Booster mode' mode.  If the prefix argument is positive, enable
the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='eglot-booster-mode)'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "eglot-booster" '("eglot-booster-"))

;;; End of scraped data

(provide 'eglot-booster-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; eglot-booster-autoloads.el ends here
