;;; kivy-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from kivy-mode.el

(add-to-list 'auto-mode-alist '("\\.kv$" . kivy-mode))
(autoload 'kivy-mode "kivy-mode" "\
Simple mode to edit kivy.

\\{kivy-mode-map}

(fn)" t)
(register-definition-prefixes "kivy-mode" '("kivy-"))

;;; End of scraped data

(provide 'kivy-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; kivy-mode-autoloads.el ends here
