;;; kconfig-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from kconfig-mode.el

(autoload 'kconfig-mode "kconfig-mode" "\
Major mode for editing Kconfig files in the Linux kernel.

(fn)" t)
(add-to-list 'auto-mode-alist '("\\Kconfig\\'" . kconfig-mode))
(register-definition-prefixes "kconfig-mode" '("kconfig-"))

;;; End of scraped data

(provide 'kconfig-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; kconfig-mode-autoloads.el ends here
