;;; go-translate-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from go-translate.el

(autoload 'gts-do-translate "go-translate" "\
Do the translate" t)
(register-definition-prefixes "go-translate" '("gts-default-translator"))


;;; Generated autoloads from gts-core.el

(register-definition-prefixes "gts-core" '("gts-"))


;;; Generated autoloads from gts-engine-bing.el

(register-definition-prefixes "gts-engine-bing" '("gts-bing-"))


;;; Generated autoloads from gts-engine-deepl.el

(register-definition-prefixes "gts-engine-deepl" '("gts-deepl-"))


;;; Generated autoloads from gts-engine-google.el

(register-definition-prefixes "gts-engine-google" '("gts-google-"))


;;; Generated autoloads from gts-engine-google-rpc.el

(register-definition-prefixes "gts-engine-google-rpc" '("gts-google-rpc-"))


;;; Generated autoloads from gts-engine-stardict.el

(register-definition-prefixes "gts-engine-stardict" '("gts-stardict-"))


;;; Generated autoloads from gts-engine-youdao.el

(register-definition-prefixes "gts-engine-youdao" '("gts-youdao-dict-e"))


;;; Generated autoloads from gts-faces.el

(register-definition-prefixes "gts-faces" '("gts-p"))


;;; Generated autoloads from gts-implements.el

(register-definition-prefixes "gts-implements" '("gts-"))

;;; End of scraped data

(provide 'go-translate-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; go-translate-autoloads.el ends here
